[phases.setup]
npmVersion = "10"
nodeVersion = "20"
pythonVersion = "3.11.9"
aptPkgs = ["python3-pip", "python3-dev", "build-essential"]

[phases.install]
cmds = [
  "npm --prefix ./frontend install",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r backend/requirements.txt"
]

[phases.build]
cmds = [
  "npm --prefix ./frontend run build",
  "mkdir -p ./frontend/out",
  "ls -la ./frontend/.next || echo '.next directory not found'",
  "ls -la ./frontend/out || echo 'out directory not found'"
]

[start]
cwd = "backend"
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port ${PORT:-3001}"
