[build]
builder = "nixpacks"
buildCommand = "npm run install:all && npm run build"

[deploy]
startCommand = "python -c \"import os, uvicorn; uvicorn.run('backend.main:app', host='0.0.0.0', port=int(os.environ.get('PORT', '3001')))\"" 
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[nixpacks]
nodejs-version = "20"
python-version = "3.11.9"
